import type {
  AttributeFieldRow,
  ProductImageRow,
  ProductRow,
  VariantRow,
} from '@/lib/types';
import type { ProductBundle } from '@/lib/completeness';

/** A fully-populated, export-ready SAREE product. Tests mutate what they need. */
export function makeProduct(overrides: Partial<ProductRow> = {}): ProductRow {
  return {
    id: 'p1',
    sku: 'HOKK-SAR-ZK-001',
    internal_reference: 'LEGACY-001',
    name: 'Amara — Zari Kota',
    name_status: 'NAME_APPROVED',
    status: 'FOUNDER_APPROVAL',
    category_id: 'cat-1',
    subcategory_id: null,
    handloom_culture_id: 'cul-1',
    region: 'Rajasthan',
    state: 'Rajasthan',
    gender: 'Women',
    target_audience: 'Adult',
    occasion: 'Festive',
    season: 'All season',
    tags: '["festive","zari"]',
    internal_notes: null,
    product_type_label: 'Saree',
    colour: 'Indigo',
    fabric: 'Kota silk',
    fabric_composition: 'Silk 60% / Cotton 40%',
    material: 'Silk blend',
    weave: 'Kota doria',
    technique: 'Khat warp weaving',
    pattern: 'Checkered',
    motifs: 'Buti',
    border: 'Zari border',
    pallu: 'Zari pallu',
    weight: 620,
    weight_unit: 'g',
    care_instructions: 'Dry clean only',
    packaging_notes: 'Muslin bag',
    saree_length: 550,
    saree_width: 115,
    blouse_included: 1,
    blouse_length: 80,
    blouse_fabric: 'Matching Kota',
    blouse_colour: 'Indigo',
    zari: 'Pure zari',
    transparency: 'Sheer',
    fall_pico_status: 'Done',
    fit: null,
    neckline: null,
    sleeve: null,
    garment_length: null,
    closure: null,
    lining: null,
    pockets: null,
    stretch: null,
    artisan_name: 'Ramesh Bunker',
    artisan_story: 'Third generation weaver from Kaithoon.',
    craft_story: 'Kota doria is woven on a pit loom in Kaithoon, Rajasthan.',
    historical_context: 'The weave travelled from Mysore to Kota in the 17th century.',
    cultural_significance: 'Worn at weddings across Rajasthan.',
    yarn: 'Silk and cotton yarn',
    zari_type: 'Pure zari',
    dyeing_method: 'Natural indigo',
    embroidery: null,
    special_techniques: 'Khat warp',
    certification: 'Handloom Mark',
    origin: 'Kaithoon, Rajasthan',
    size_guide_id: null,
    length_unit: 'cm',
    measurements: '[{"label":"Saree length","value":"550","unit":"cm"}]',
    short_description: 'A handwoven Zari Kota saree in indigo.',
    full_description: 'Woven on a pit loom in Kaithoon, this Zari Kota saree pairs a sheer kota base with a pure zari border.',
    story: 'Amara means immortal. This saree was woven for a bride who wanted her grandmother\'s weave reborn.',
    about_the_weave: 'Kota doria is built on a square-check warp called khat.',
    about_the_artisan: 'Ramesh has been at the loom for twenty-two years.',
    details: '["Pure zari border","Blouse piece included","Handwoven"]',
    care: 'Dry clean only',
    shipping_notes: 'Ships in 3 days',
    price: 12500,
    compare_at_price: 15000,
    cost_price: 6000,
    currency: 'INR',
    taxable: 1,
    tax_code: null,
    discount_eligible: 1,
    inventory_qty: 1,
    inventory_policy: 'deny',
    inventory_tracker: 'shopify',
    track_inventory: 1,
    seo_title: 'Amara — Zari Kota Saree | House of Kala Katha',
    seo_description: 'Handwoven Zari Kota saree in indigo with a pure zari border.',
    handle: 'amara-zari-kota',
    handle_locked: 0,
    shopify_status: 'draft',
    published: 0,
    published_at: null,
    template_suffix: null,
    vendor: 'House of Kala Katha',
    shopify_product_id: null,
    last_exported_at: null,
    last_export_run_id: null,
    requires_shipping: 1,
    hs_code: null,
    country_of_origin: 'IN',
    assignee_id: 'u1',
    created_by_id: 'u1',
    modified_by_id: 'u1',
    completeness_score: 0,
    readiness_state: 'BLOCKED',
    readiness_score: 0,
    readiness_issues: '[]',
    photography_complete: 0,
    photography_required: 0,
    is_archived: 0,
    created_at: '2026-09-01T10:00:00.000Z',
    updated_at: '2026-09-10T10:00:00.000Z',
    template_key: 'SAREE',
    ...overrides,
  } as ProductRow;
}

export function makeSlot(id: string, key: string, required: boolean, label = key) {
  return { id, key, label, is_required: required ? 1 : 0 };
}

export function makeImage(overrides: Partial<ProductImageRow> = {}): ProductImageRow {
  return {
    id: 'img-1',
    product_id: 'p1',
    slot_id: 'slot-hero',
    file_name: 'HOKK-SAR-ZK-001-HERO.jpg',
    storage_key: 'original/HOKK-SAR-ZK-001/HOKK-SAR-ZK-001-HERO.jpg',
    path: '/tmp/x.jpg',
    public_url: 'https://cdn.example.com/hero.jpg',
    mime_type: 'image/jpeg',
    bytes: 2_000_000,
    width: 2400,
    height: 3000,
    folder: 'FINAL',
    alt_text: 'Amara Zari Kota saree draped on model',
    sort_order: 0,
    is_primary: 1,
    review_status: 'APPROVED',
    reviewed_by_id: 'u2',
    reviewed_at: '2026-09-09T10:00:00.000Z',
    storage_backend: 'LOCAL',
    drive_file_id: null,
    drive_folder_id: null,
    checksum: 'abc',
    duplicate_of_id: null,
    uploaded_by_id: 'u2',
    created_at: '2026-09-08T10:00:00.000Z',
    updated_at: '2026-09-08T10:00:00.000Z',
    slot_key: 'HERO',
    ...overrides,
  } as ProductImageRow;
}

export function makeVariant(overrides: Partial<VariantRow> = {}): VariantRow {
  return {
    id: 'v1',
    product_id: 'p1',
    sku: 'HOKK-SAR-ZK-001',
    title: 'Default',
    position: 1,
    option1_name: 'Title',
    option1_value: 'Default Title',
    option2_name: null,
    option2_value: null,
    option3_name: null,
    option3_value: null,
    price: 12500,
    compare_at_price: 15000,
    cost_price: 6000,
    inventory_qty: 1,
    weight: 620,
    weight_unit: 'g',
    barcode: null,
    taxable: 1,
    requires_shipping: 1,
    inventory_policy: 'deny',
    inventory_tracker: 'shopify',
    track_inventory: 1,
    image_url: null,
    is_active: 1,
    created_at: '2026-09-01T10:00:00.000Z',
    updated_at: '2026-09-01T10:00:00.000Z',
    ...overrides,
  } as VariantRow;
}

export function makeAttribute(overrides: Partial<AttributeFieldRow> = {}): AttributeFieldRow {
  return {
    id: 'f1',
    template_key: 'SAREE',
    group_key: 'SPECIFICATION',
    group_label: 'Product details',
    key: 'zari_purity',
    label: 'Zari purity',
    field_type: 'SELECT',
    options: '[]',
    unit: null,
    is_required: 1,
    track_gap: 1,
    sort_order: 1,
    is_archived: 0,
    created_at: '2026-09-01T10:00:00.000Z',
    updated_at: '2026-09-01T10:00:00.000Z',
    value: 'Pure zari',
    is_missing: 0,
    note: null,
    ...overrides,
  } as AttributeFieldRow;
}

/** All six required saree slots filled, so photography is never the blocker. */
export function sareeSlots() {
  return [
    makeSlot('slot-hero', 'HERO', true, 'Hero / model'),
    makeSlot('slot-full', 'FULL', true, 'Full look'),
    makeSlot('slot-detail', 'DETAIL', true, 'Detail'),
    makeSlot('slot-pallu', 'PALLU', true, 'Pallu'),
    makeSlot('slot-border', 'BORDER', true, 'Border'),
    makeSlot('slot-fabric', 'FABRIC', true, 'Fabric / weave'),
    makeSlot('slot-blouse', 'BLOUSE', false, 'Blouse'),
    makeSlot('slot-editorial', 'EDITORIAL', false, 'Editorial'),
  ];
}

export function sareeImages() {
  return sareeSlots()
    .filter((slot) => slot.is_required === 1)
    .map((slot, index) =>
      makeImage({
        id: `img-${slot.key}`,
        slot_id: slot.id,
        slot_key: slot.key,
        file_name: `HOKK-SAR-ZK-001-${slot.key}.jpg`,
        sort_order: index,
        is_primary: index === 0 ? 1 : 0,
      }),
    );
}

export function makeBundle(overrides: Partial<ProductBundle> = {}): ProductBundle {
  return {
    product: makeProduct(),
    variants: [makeVariant()],
    images: sareeImages(),
    collections: [{ id: 'col-1', name: 'Handloom Stories' }],
    slots: sareeSlots(),
    attributes: [makeAttribute()],
    gaps: [],
    ...overrides,
  };
}
